export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FILTER_PRODUCTS_BY_SIZE = "FILTER_PRODUCTS_BY_SIZE";
export const ORDER_PRODUCTS_BY_PRICE = "ORDER_PRODUCTS_BY_PRICE";

export const FETCH_ITEMS = "FETCH_ITEMS";
export const ADD_TO_CART = "ADD_TO_CART";
export const UPDATE_CART_ITEM = "UPDATE_CART_ITEM";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";

export const CREATE_CART = "CREATE_CART";
export const CLEAR_CART = "CLEAR_CART";
export const FETCH_CARTS = "FETCH_CARTS";