export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FILTER_PRODUCTS = "FILTER_PRODUCTS";
export const ORDER_PRODUCTS = "ORDER_PRODUCTS";

export const FETCH_ITEMS = "FETCH_ITEMS";
export const ADD_TO_CART = "ADD_TO_CART";
export const UPDATE_CART_ITEM = "UPDATE_CART_ITEM";
export const CLEAR_CART_ITEMS = "CLEAR_CART_ITEMS";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";

export const UPDATE_CART = "UPDATE_CART";
export const FETCH_CARTS = "FETCH_CARTS";